# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 80
    #打开注释，则通过【http://localhost/leader】访问
    #context-path: /leader-college

spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 500MB
            max-request-size: 20MB
            enabled: true
    resources: # 指定静态资源的路径
        static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml
# 微信小程序配置
wechat:
  miniapp:
    appid: 111
    secret: 111
    token: 111
    aesKey: 111
    msgDataFormat: JSON
    mchId:
    mchKey:
    subAppId:
    subMchId:
    keyPath:
